//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberArtwork
    {
        public int ArtworkID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string ArtworkTitle { get; set; }
        public string ArtworkImage { get; set; }
        public string Category { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
