//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_info
    {
        public int ArtworkID { get; set; }
        public int user_id { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string cardname { get; set; }
        public string cardnumber { get; set; }
        public string expdate { get; set; }
        public Nullable<int> total_amt { get; set; }
        public int cvv { get; set; }
    
        public virtual user_info user_info { get; set; }
    }
}
